[tool.ruff]
target-version = "py313"
line-length = 120
exclude = [  # Исключаем старые задания, чтобы на них не применялись новые правила
    "src/conditions/*.py",
    "src/cycles/*.py",
    "src/function/*.py",
    "src/massive/*.py",
    "src/range/even_uneven.py",
    "src/range/tiri_piri.py",
]

[tool.ruff.lint]
select = ["B", "COM", "N", "E", "ISC", "W", "F", "RET", "SIM", "PL"]

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
# Start off with these
warn_unused_configs = true

warn_redundant_casts = true

warn_unused_ignores = true


# Getting this passing should be easy
strict_equality = true


# Strongly recommend enabling this one as soon as you can
check_untyped_defs = true


# These shouldn't be too much additional work, but may be tricky to
# get passing if you use a lot of untyped libraries
disallow_subclassing_any = true

disallow_untyped_decorators = true

disallow_any_generics = true


# These next few are various gradations of forcing use of type annotations
disallow_untyped_calls = true

disallow_incomplete_defs = true

disallow_untyped_defs = true


# This one isn't too hard to get passing, but return on investment is lower
no_implicit_reexport = true


# This one can be tricky to get passing if you use a lot of untyped libraries
warn_return_any = true


# This one is a catch-all flag for the rest of strict checks that are technically
# correct but may not be practical
extra_checks = true
